// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: oraclenode.proto

package iop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest_Type int32

const (
	ValidateRequest_unknown     ValidateRequest_Type = 0
	ValidateRequest_block       ValidateRequest_Type = 1
	ValidateRequest_transaction ValidateRequest_Type = 2
)

// Enum value maps for ValidateRequest_Type.
var (
	ValidateRequest_Type_name = map[int32]string{
		0: "unknown",
		1: "block",
		2: "transaction",
	}
	ValidateRequest_Type_value = map[string]int32{
		"unknown":     0,
		"block":       1,
		"transaction": 2,
	}
)

func (x ValidateRequest_Type) Enum() *ValidateRequest_Type {
	p := new(ValidateRequest_Type)
	*p = x
	return p
}

func (x ValidateRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_oraclenode_proto_enumTypes[0].Descriptor()
}

func (ValidateRequest_Type) Type() protoreflect.EnumType {
	return &file_oraclenode_proto_enumTypes[0]
}

func (x ValidateRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateRequest_Type.Descriptor instead.
func (ValidateRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{5, 0}
}

type SendRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R *RDeal `protobuf:"bytes,1,opt,name=R,proto3" json:"R,omitempty"`
}

func (x *SendRRequest) Reset() {
	*x = SendRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oraclenode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRRequest) ProtoMessage() {}

func (x *SendRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRRequest.ProtoReflect.Descriptor instead.
func (*SendRRequest) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{0}
}

func (x *SendRRequest) GetR() *RDeal {
	if x != nil {
		return x.R
	}
	return nil
}

type RDeal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R     []byte `protobuf:"bytes,1,opt,name=R,proto3" json:"R,omitempty"`
	Index []byte `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *RDeal) Reset() {
	*x = RDeal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oraclenode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDeal) ProtoMessage() {}

func (x *RDeal) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDeal.ProtoReflect.Descriptor instead.
func (*RDeal) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{1}
}

func (x *RDeal) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *RDeal) GetIndex() []byte {
	if x != nil {
		return x.Index
	}
	return nil
}

type SendRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendRResponse) Reset() {
	*x = SendRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oraclenode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRResponse) ProtoMessage() {}

func (x *SendRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRResponse.ProtoReflect.Descriptor instead.
func (*SendRResponse) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{2}
}

type ChanllengeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       []byte `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Chanllenge []byte `protobuf:"bytes,2,opt,name=Chanllenge,proto3" json:"Chanllenge,omitempty"`
}

func (x *ChanllengeRequest) Reset() {
	*x = ChanllengeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oraclenode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChanllengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChanllengeRequest) ProtoMessage() {}

func (x *ChanllengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChanllengeRequest.ProtoReflect.Descriptor instead.
func (*ChanllengeRequest) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{3}
}

func (x *ChanllengeRequest) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ChanllengeRequest) GetChanllenge() []byte {
	if x != nil {
		return x.Chanllenge
	}
	return nil
}

type ChanllengeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proof []byte `protobuf:"bytes,1,opt,name=Proof,proto3" json:"Proof,omitempty"`
}

func (x *ChanllengeResponse) Reset() {
	*x = ChanllengeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oraclenode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChanllengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChanllengeResponse) ProtoMessage() {}

func (x *ChanllengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChanllengeResponse.ProtoReflect.Descriptor instead.
func (*ChanllengeResponse) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{4}
}

func (x *ChanllengeResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ValidateRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=iop.ValidateRequest_Type" json:"type,omitempty"`
	Hash []byte               `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oraclenode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateRequest) GetType() ValidateRequest_Type {
	if x != nil {
		return x.Type
	}
	return ValidateRequest_unknown
}

func (x *ValidateRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash        []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Valid       bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	BlockNumber int64  `protobuf:"varint,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Signature   []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	R           []byte `protobuf:"bytes,5,opt,name=R,proto3" json:"R,omitempty"`
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oraclenode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ValidateResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ValidateResponse) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

var File_oraclenode_proto protoreflect.FileDescriptor

var file_oraclenode_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x69, 0x6f, 0x70, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x01, 0x52, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x69, 0x6f, 0x70, 0x2e, 0x52, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x01,
	0x52, 0x22, 0x2b, 0x0a, 0x05, 0x52, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x52, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x52, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x0f,
	0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x47, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x43, 0x68,
	0x61, 0x6e, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x22, 0x85, 0x01, 0x0a, 0x0f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x70, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x2f, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x22, 0x8a, 0x01, 0x0a,
	0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x52,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x52, 0x32, 0xb4, 0x01, 0x0a, 0x0a, 0x4f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x12, 0x11, 0x2e, 0x69, 0x6f, 0x70, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x69, 0x6f, 0x70, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x69, 0x6f, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x69, 0x6f, 0x70,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12,
	0x16, 0x2e, 0x69, 0x6f, 0x70, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x6f, 0x70, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x69, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_oraclenode_proto_rawDescOnce sync.Once
	file_oraclenode_proto_rawDescData = file_oraclenode_proto_rawDesc
)

func file_oraclenode_proto_rawDescGZIP() []byte {
	file_oraclenode_proto_rawDescOnce.Do(func() {
		file_oraclenode_proto_rawDescData = protoimpl.X.CompressGZIP(file_oraclenode_proto_rawDescData)
	})
	return file_oraclenode_proto_rawDescData
}

var file_oraclenode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oraclenode_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_oraclenode_proto_goTypes = []interface{}{
	(ValidateRequest_Type)(0),  // 0: iop.ValidateRequest.Type
	(*SendRRequest)(nil),       // 1: iop.SendRRequest
	(*RDeal)(nil),              // 2: iop.RDeal
	(*SendRResponse)(nil),      // 3: iop.SendRResponse
	(*ChanllengeRequest)(nil),  // 4: iop.ChanllengeRequest
	(*ChanllengeResponse)(nil), // 5: iop.ChanllengeResponse
	(*ValidateRequest)(nil),    // 6: iop.ValidateRequest
	(*ValidateResponse)(nil),   // 7: iop.ValidateResponse
}
var file_oraclenode_proto_depIdxs = []int32{
	2, // 0: iop.SendRRequest.R:type_name -> iop.RDeal
	0, // 1: iop.ValidateRequest.type:type_name -> iop.ValidateRequest.Type
	1, // 2: iop.OracleNode.SendR:input_type -> iop.SendRRequest
	6, // 3: iop.OracleNode.Validate:input_type -> iop.ValidateRequest
	4, // 4: iop.OracleNode.Chanllenge:input_type -> iop.ChanllengeRequest
	3, // 5: iop.OracleNode.SendR:output_type -> iop.SendRResponse
	7, // 6: iop.OracleNode.Validate:output_type -> iop.ValidateResponse
	5, // 7: iop.OracleNode.Chanllenge:output_type -> iop.ChanllengeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oraclenode_proto_init() }
func file_oraclenode_proto_init() {
	if File_oraclenode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oraclenode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oraclenode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RDeal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oraclenode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oraclenode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChanllengeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oraclenode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChanllengeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oraclenode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oraclenode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oraclenode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oraclenode_proto_goTypes,
		DependencyIndexes: file_oraclenode_proto_depIdxs,
		EnumInfos:         file_oraclenode_proto_enumTypes,
		MessageInfos:      file_oraclenode_proto_msgTypes,
	}.Build()
	File_oraclenode_proto = out.File
	file_oraclenode_proto_rawDesc = nil
	file_oraclenode_proto_goTypes = nil
	file_oraclenode_proto_depIdxs = nil
}
